#! /bin/bash
EmailAddress=it@forlongs.co.nz
MailServer=fibre.forlongs.co.nz

echo -n "MAKE SURE YOU'RE RUNNING AS ROOT! And make sure you've modified the mail server in this file -- currently $MailServer.  If not, press Ctrl+C NOW."
sleep 1
echo -n "."
sleep 1
echo -n "."
sleep 1
echo -n "."
sleep 1
echo -n "."
sleep 1

## Tweaks from https://klaver.it/linux/debian-security.txt:

# remove or take away permissions of all system tools that can be used to download files at the command-line
chmod 700 /usr/bin/wget /usr/bin/curl /usr/bin/GET /usr/bin/ftp /usr/bin/telnet 2> /dev/null
dpkg -P lynx links 2> /dev/null

# Knobble auto-installed compiler
mv /usr/bin/as ~

# Disable cron-jobs (exept for the root user)
echo root > /etc/cron.allow
service cron restart

# Let the server fix it's filesystem automatically when errors are found
echo "FSCKFIX=yes" >> /etc/default/rcS

## Tweaks from fmarier at http://feeding.cloud.geek.nz/posts/usual-server-setup/

apt-get update && apt-get upgrade -y
apt-get install sudo openssh-server fail2ban unattended-upgrades debsums ssmtp unzip curl -y

# Download Lynis
cd ~
wget https://github.com/CISOfy/lynis/archive/master.zip --no-check-certificate
unzip master.zip

# Set up SSMTP
echo -e "mailhub="$MailServer"\nroot="$EmailAddress"\nhostname="$(hostname -f) > /etc/ssmtp/ssmtp.conf

# most tools send e-mail to root@localhost; redirect this to a working e-mail address:
echo "root: "$EmailAddress >> /etc/aliases
newaliases

# Entropy & time-keeping
apt-get install haveged rng-tools ntp -y
echo tpm_rng >> /etc/modules

# Disable USB & Firewire storage
echo -e "blacklist usb-storage\nblacklist ohci1394\nblacklist sbp2\nblacklist dv1394\nblacklist raw1394\nblacklist video1394\nblacklist firewire-ohci\nblacklist firewire-sbp2" > /etc/modprobe.d/blacklist_storage.conf

# Have debsums check checksums daily
sed -i 's/CRON_CHECK=never/CRON_CHECK=daily/g' /etc/default/debsums

# Ignore the missing 'as' compiler
echo -e "^/usr/bin/as$" > /etc/debsums-ignore

addgroup ssh-user
usermod -aG ssh-user it
usermod -aG sudo it

# Configure Unattended-Upgrades.  NOTE this config will reboot at 2am if reboot required
dpkg-reconfigure -plow unattended-upgrades 
echo -e "Unattended-Upgrade::Origins-Pattern {\n\"o=Debian,n=jessie\";\n\"o=Debian,n=jessie-updates\";\n\"o=Debian,n=jessie,l=Debian-Security\";\n};\nUnattended-Upgrade::Mail \"alerts@forlongs.co.nz\";\nUnattended-Upgrade::MailOnlyOnError \"true\";\nUnattended-Upgrade::Remove-Unused-Dependencies \"true\";\nUnattended-Upgrade::Automatic-Reboot \"true\";\nUnattended-Upgrade::Automatic-Reboot-Time \"02:00\";\n" > /etc/apt/apt.conf.d/50unattended-upgrades


# Install and enable AppArmor; disable IPv6 stack
apt-get install apparmor apparmor-profiles apparmor-utils -y
perl -pi -e 's,GRUB_CMDLINE_LINUX="(.*)"$,GRUB_CMDLINE_LINUX="$1 apparmor=1 security=apparmor ipv6.disable=1",' /etc/default/grub
for f in *.* ; do aa-enforce /etc/apparmor.d/$f; done


# Tweaks to sysctl.conf kernel settings
cd ~
wget --no-check-certificate https://klaver.it/linux/sysctl.conf
# Change Michiel Klaver's default settings
sed -i 's/net.core.default_qdisc = fq/net.core.default_qdisc = fq_codel/g' sysctl.conf 
sed -i 's/net.ipv4.tcp_congestion_control = htcp/net.ipv4.tcp_congestion_control = cubic/g' sysctl.conf
echo -e "kernel.core_pattern=/var/crash/core-%e-%s-%u-%g-%p-%t\n" >> sysctl.conf
echo -e "kernel.modules_disabled=1\n" >> sysctl.conf
mv sysctl.conf /etc -f

# Commit kernel changes
update-grub


# Create 4096-bit RSA key
ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa4096 < /dev/null

# Create ~/.ssh/authorized_keys
mkdir /home/it/.ssh
echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGOOmq7XITJLExEheDCdDvlAyzSbMU0/PWXWoxc5V/5o Eric's PC" > /home/it/.ssh/authorized_keys
chown it:it /home/it/.ssh
chown it:it /home/it/.ssh/*
chmod 600 /home/it/.ssh/authorized_keys

# Download and overwrite SSHD config file
wget --no-check-certificate https://raw.githubusercontent.com/rhyven/ssh/master/sshd_config
mv sshd_config /etc/ssh/sshd_config -f
service ssh restart

# Security tweaks for /etc/profile
echo -e "TMOUT=300\nreadonly TMOUT\nexport TMOUT\numask 027" >> /etc/profile
sed -i 's/UMASK\t\t022/UMASK\t\t027/g' /etc/login.defs
sed -i 's/umask 022/umask 027/g' /etc/init.d/rc

# Use NZ ntp pool
sed -i 's/debian.pool.ntp/nz.pool.ntp/g' /etc/ntp.conf

# Build sysprep2
# Install Tripwire and Tiger
echo "sudo apt-get install tripwire tiger -y" > sysprep2

# Fix Tiger for Linux 4 - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=785589
echo -e "cd /usr/lib/tiger/systems/Linux/\nsudo ln -s 3 4" >> sysprep2

# Tell Tiger that sshd and ntpd are both OK
echo -e "sudo sed -i 's/Tiger_Listening_ValidProcs='\''/Tiger_Listening_ValidProcs='\''sshd|ntpd''/g' /etc/tiger/tigerrc" >> sysprep2

# Configure Tripwire to send emails
echo "sudo sed -i 's/localhost/$MailServer/g' /etc/tripwire/twcfg.txt" >> sysprep2
echo "sudo twadmin --create-cfgfile -S /etc/tripwire/site.key /etc/tripwire/twcfg.txt" >> sysprep2
echo "tripwire --test --email "$EmailAddress >> sysprep2
# Purge unwanted packages
echo "apt-get purge ufw iptables john john-data rpcbind exim4 sendmail sendmail-* postfix -y 2> /dev/null"  >> sysprep2
# Enable AllowGroups under sshd_config (you're using SSH already, right???)
echo "sudo sed -i 's/# AllowGroups/AllowGroups/g' /etc/ssh/sshd_config" >> sysprep2
# Notes for next boot
echo "echo Check http://www.linuxquestions.org/questions/linux-newbie-8/tripwire-help-4175478323/"   >> sysprep2
echo "echo and https://www.digitalocean.com/community/tutorials/how-to-use-tripwire-to-detect-server-intrusions-on-an-ubuntu-vps"  >> sysprep2
echo "echo for help on setting up Tripwire."  >> sysprep2
echo "echo NOTE - you probably don't need /proc/dma; /proc/scsi; or /proc/kcore."  >> sysprep2
echo "echo Execute ./moduli when you've got some time to kill."   >> sysprep2

echo -e "ssh-keygen -G /tmp/moduli -b 4096 && ssh-keygen -T /etc/ssh/moduli -f /tmp/moduli" > moduli
echo -e "rm ./moduli" >> moduli
chmod a+x moduli

echo "REBOOT NOW, and then run bash ./sysprep2"
rm ./sysprep
